set-option -sa terminal-overrides ",xterm*:Tc"

# Controls {{{

set-window-option -g mode-keys vi
set -g mouse on

# Change Index
set -g base-index 1
set -g pane-base-index 1

# }}}

set -g status-style 'bg=#222222 fg=#ffffff'
set -g set-titles on
set -g set-titles-string 'tmux - #{session_title} (#{window_index}/#{session_windows} #{window_name})'

# Plugins {{{

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'

# Session persistence {{{

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-nvim 'session'

set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'

# }}}

# Colorscheme
set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'dark'

# }}}

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
