" Generated by vim-plug
" Fri 20 Mar 2026 02:02:18 PM EDT
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['AutoComplPop'].commit = '0b075cf5e6ef05584ef6377e116e8d0fe1f8f788'
silent! let g:plugs['Colorizer'].commit = 'f5d69c0dea9f36e2eb025c7d86cc62b5a0d8af62'
silent! let g:plugs['auto-omni'].commit = 'ff91f0285a9edc5d410ae41a57cc40a692d8a68b'
silent! let g:plugs['blink.cmp'].commit = '78336bc89ee5365633bcf754d93df01678b5c08f'
silent! let g:plugs['dbext.vim'].commit = '14f3d530b6189dc3f97edfa70b7a36006e21148c'
silent! let g:plugs['fzf'].commit = '259e841a77a8eb562444440a6f57ee5e89ec106e'
silent! let g:plugs['fzf.vim'].commit = '34a564c81f36047f50e593c1656f4580ff75ccca'
silent! let g:plugs['mason-lspconfig.nvim'].commit = 'a979821a975897b88493843301950c456a725982'
silent! let g:plugs['mason.nvim'].commit = '44d1e90e1f66e077268191e3ee9d2ac97cc18e65'
silent! let g:plugs['nerdtree'].commit = '690d061b591525890f1471c6675bcb5bdc8cdff9'
silent! let g:plugs['nvim-lspconfig'].commit = '841c6d4139aedb8a3f2baf30cef5327371385b93'
silent! let g:plugs['nvim-treesitter'].commit = '42fc28ba918343ebfd5565147a42a26580579482'
silent! let g:plugs['splitjoin.vim'].commit = '9ce4fb4f0538cff02a57a393057b7ab371324483'
silent! let g:plugs['tabular'].commit = '12437cd1b53488e24936ec4b091c9324cafee311'
silent! let g:plugs['undotree'].commit = '6fa6b57cda8459e1e4b2ca34df702f55242f4e4d'
silent! let g:plugs['vim-abolish'].commit = 'dcbfe065297d31823561ba787f51056c147aa682'
silent! let g:plugs['vim-airline'].commit = '512456e425409ec58627bd839fbb85d449d8cbc1'
silent! let g:plugs['vim-characterize'].commit = 'a8bffac6cead6b2869d939ecad06312b187a4c79'
silent! let g:plugs['vim-commentary'].commit = '64a654ef4a20db1727938338310209b6a63f60c9'
silent! let g:plugs['vim-dadbod'].commit = '6d1d41da4873a445c5605f2005ad2c68c99d8770'
silent! let g:plugs['vim-fugitive'].commit = '3b753cf8c6a4dcde6edee8827d464ba9b8c4a6f0'
silent! let g:plugs['vim-gitgutter'].commit = '55b368d4c68541775b4b253d3c98d3145b695c24'
silent! let g:plugs['vim-markdown'].commit = 'f9f845f28f4da33a7655accb22f4ad21f7d9fb66'
silent! let g:plugs['vim-obsession'].commit = 'ed9dfc7c2cc917ace8b24f4f9f80a91e05614b63'
silent! let g:plugs['vim-polyglot'].commit = 'f061eddb7cdcc614c8406847b2bfb53099832a4e'
silent! let g:plugs['vim-ps1'].commit = '839cec1550e09fc902c74103053e9e765051083d'
silent! let g:plugs['vim-repeat'].commit = '65846025c15494983dafe5e3b46c8f88ab2e9635'
silent! let g:plugs['vim-signature'].commit = '6bc3dd1294a22e897f0dcf8dd72b85f350e306bc'
silent! let g:plugs['vim-surround'].commit = '3d188ed2113431cf8dac77be61b842acb64433d9'
silent! let g:plugs['vim-unimpaired'].commit = 'db65482581a28e4ccf355be297f1864a4e66985c'

PlugUpdate!

